#!/bin/bash
$(bundle show wkhtmltopdf-binary)/bin/wkhtmltopdf --page-size Letter \
  --margin-top 0.75in --margin-left 0.75in \
  --margin-right 0.75in --margin-bottom 0.75in \
  --print-media-type --dpi 300 \
  _site/resume/index.html _site/resume.pdf
